// Desc: List of sitios in the barangay
export const Sitios = [
    "Asia I",
    "Asia II",
    "Balagbag Araw/Kapatangan",
    "Buntog",
    "Canlubang",
    "Carmel",
    "Casmicehos",
    "Ceris I & II",
    "Ceris III",
    "Happy Valley",
    "Kapatagan B-1",
    "Locomotive",
    "Majada-In",
    "Mangumit I",
    "Mangumit II",
    "Manfil",
    "MCDC",
    "Nuvali",
    "Old Stable",
    "Palao",
    "Putol",
    "Silangan",
  ];